### ISSUE TITLE
USER STORY : User friendly home page

### ISSUE THREAD

**Issue by Mohamedaliabdikarim** [Mohamedaliabdikarim/RBS#1]
As a **customer**, I can **visit** the homepage of my favorite restaurant so that I can **view the services provided.** 

**Acceptance Criteria:**

1. The user can visit the websites to view services from the home page.
2. The user can be directed to different servicec of the website.
3. The user can view critical information about the resturrant

**Tasks**

    

- [x]     Create a base temple and extend it in home view template
- [x]    Create home.html template for Home page with basic skeleton
- [x]     Update urls.py
- [x]     Add bootstrap navbar
- [x]     Add custom footer

**Comment by Mohamedaliabdikarim** [comment]
the footer is not right

**Comment by Mohamedaliabdikarim** [comment]
Fixed the problem with the footer

**Comment by Mohamedaliabdikarim** [comment]
completed.
