### ISSUE TITLE
USER STORY : <Navigation>

### ISSUE THREAD

**Issue by Mohamedaliabdikarim** [Mohamedaliabdikarim/RBS#2]
As a **user**, I can **easily locate the navigation area**  no the website so that I can access different parts of it without hassle.

**Acceptance Criteria:**

1.The header is prominently displayed at the top of the pag
2.All icons take the user to the relevant page.

**Tasks**

- [ ] Add  logo  to the NavBar

- [x] Create relevant pages

- [x] Add links to NavBar items

- [x] Connect urls

**Comment by Mohamedaliabdikarim** [comment]
completed.
