### ISSUE TITLE
USER STORY : <sign up>

### ISSUE THREAD

**Issue by Mohamedaliabdikarim** [Mohamedaliabdikarim/RBS#3]
As a **guest user**, I want **to register on the website to** access its functionality and content.

**Acceptance Criteria:**

1.When a user is not registered or signed in, they should see registration and login buttons in the navigation bar.
2. Clicking on the Sign Up button should redirect the user to a registration form.

**Tasks:**

   

- [x]  Modify links in the navigation bar located in the header.html template.
- [x]     Update the signup.html template in the templates/allauth directory.
- [x]     Apply styling to the form using the crispy filter.

**Comment by Mohamedaliabdikarim** [comment]
completed
