### ISSUE TITLE
USER STORY : <TILTLE>

### ISSUE THREAD

**Issue by Mohamedaliabdikarim** [Mohamedaliabdikarim/RBS#6]
As a user I can enter my personal details so that I can create an account with on the webside and be contacted in case of need

**Acceptance Criteria**

1.  User is taken to a page where they can easily enter all required information (first name, last name, phone number).
2.  Created user_profile page saves successfully into the database.

**Tasks**

    

- [x] Create User Profile set-up page
- [x]     Create form for the user to fill in
- [x]    Add url path to urls.py

**Comment by Mohamedaliabdikarim** [comment]
completed.
