### ISSUE TITLE
USER STORY : <Delete reservation>

### ISSUE THREAD

**Issue by Mohamedaliabdikarim** [Mohamedaliabdikarim/RBS#7]
As a **registered** diner, I can **cancel** my table reservation so that I can free up the table and inform the restaurant.

**Acceptance Criteria**

1.  When viewing my table reservation, I can choose to cancel it by clicking on the Cancel                 Reservation button. 
2.  Only a signed-in diner who made the reservation can cancel it.
3. The diner is asked to confirm their decision to cancel the reservation in order to prevent accidental cancellations.

**Tasks**

 

- [x]    Develop a cancellation view
- [x]     Integrate and link the cancellation button with the table reservation details.
- [x]     Ensure the diner is logged in and the owner of the reservation

**Comment by Mohamedaliabdikarim** [comment]
completed
