### ISSUE TITLE
USER STORY : <update>

### ISSUE THREAD

**Issue by Mohamedaliabdikarim** [Mohamedaliabdikarim/RBS#8]
As a **diner**, I can edit my reservation to update my booking details.

**Acceptance Criteria**

1.  When the Edit button is clicked, the user is directed to the Reservation Update Form.
2. The form displays prefilled fields with the diner's original reservation information, which can be edited.
3.  The placeholder text disappears as the user starts editing.
4.   Any changes made are saved in the database.

**Tasks**

   

- [x]  Implement functionality for the 'Edit' button to redirect the user to the Reservation Update page.
- [x]     Display a form with editable fields for the reservation details.
- [x]     Provide a 'Save' button to submit and save the changes in the database.

**Comment by Mohamedaliabdikarim** [comment]
completed
